import React, { useCallback, useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ChevronRight, File, FileImage, FileText, Folder, FolderPlus, MessageCircle, RefreshCw, Search, Sparkles, Trash2, Upload } from 'lucide-react';
import './styles.css';

const API_ROOT = (import.meta.env.VITE_STORAGE_API || 'http://127.0.0.1:8791/api/storage').replace(/\/api\/storage$/, '');
const API = `${API_ROOT}/api/storage`;
const formatSize = (size) => size < 1024 ? `${size} B` : size < 1024 ** 2 ? `${(size / 1024).toFixed(1)} KB` : `${(size / 1024 ** 2).toFixed(1)} MB`;
const fileIcon = (name) => name.match(/\.(png|jpe?g|gif|webp)$/i) ? FileImage : name.match(/\.(docx?|pdf|txt|xlsx?)$/i) ? FileText : File;

function App() {
  const [prefix, setPrefix] = useState(''); const [folders, setFolders] = useState([]); const [files, setFiles] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [query, setQuery] = useState(''); const [uploading, setUploading] = useState(0); const [searchMode, setSearchMode] = useState('chat'); const [searchType, setSearchType] = useState('image'); const [searching, setSearching] = useState(false); const [results, setResults] = useState([]); const [searchError, setSearchError] = useState(''); const [chatQuery, setChatQuery] = useState(''); const [chatMessages, setChatMessages] = useState([]); const [chatting, setChatting] = useState(false); const chatSession = useRef(`web-${crypto.randomUUID()}`); const input = useRef(null);
  const load = useCallback(async () => { setLoading(true); setError(''); try { const res = await fetch(`${API}?prefix=${encodeURIComponent(prefix)}`); const data = await res.json(); if (!res.ok) throw new Error(data.error); setFolders(data.folders || []); setFiles(data.files || []); } catch (e) { setError(e.message || '无法连接存储服务'); } finally { setLoading(false); } }, [prefix]);
  useEffect(() => { load(); }, [load]);
  const upload = async (event) => { const selected = [...(event.target.files || [])]; if (!selected.length) return; setUploading(selected.length); for (const file of selected) { await fetch(`${API}?key=${encodeURIComponent(prefix + file.name)}`, { method: 'POST', headers: { 'Content-Type': file.type || 'application/octet-stream' }, body: file }); setUploading((count) => count - 1); } event.target.value = ''; load(); };
  const createFolder = async () => { const name = window.prompt('请输入文件夹名称'); const clean = name?.trim().replaceAll('/', ''); if (!clean) return; const res = await fetch(`${API}?key=${encodeURIComponent(prefix + clean + '/')}`, { method: 'POST', headers: { 'Content-Type': 'application/x-directory' }, body: '' }); if (!res.ok) { const data = await res.json(); window.alert(data.error || '创建失败'); return; } load(); };
  const remove = async (key) => { if (!window.confirm(`确定删除 ${key}？`)) return; await fetch(`${API}?key=${encodeURIComponent(key)}`, { method: 'DELETE' }); load(); };
  const removeFolder = async (folder) => { if (!window.confirm(`确定删除文件夹“${folder}”及其中全部对象？此操作不可撤销。`)) return; const res = await fetch(`${API}?folder=${encodeURIComponent(folder)}`, { method: 'DELETE' }); const data = await res.json(); if (!res.ok) window.alert(data.error || '删除失败'); load(); };
  const semanticSearch = async (event) => { event?.preventDefault(); const value = query.trim(); if (!value) return; setSearching(true); setSearchError(''); try { const res = await fetch(`${API_ROOT}/api/search`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ query: value, type: searchType }) }); const data = await res.json(); if (!res.ok) throw new Error(data.error); setResults(data.results || []); } catch (e) { setSearchError(e.message || 'MetaInsight 查询失败'); setResults([]); } finally { setSearching(false); } };
  const sendChat = async (event) => { event?.preventDefault(); const value = chatQuery.trim(); if (!value || chatting) return; setChatQuery(''); setChatMessages((items) => [...items, { role: 'user', content: value }, { role: 'assistant', content: '' }]); setChatting(true); try { const res = await fetch(`${API_ROOT}/api/adp/chat`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ content: value, visitorId: chatSession.current, sessionId: chatSession.current }) }); if (!res.ok || !res.body) throw new Error((await res.text()) || 'ADP 对话失败'); const reader = res.body.getReader(); const decoder = new TextDecoder(); let buffer = ''; while (true) { const part = await reader.read(); if (part.done) break; buffer += decoder.decode(part.value, { stream: true }); const chunks = buffer.split(/\n\n/); buffer = chunks.pop() || ''; for (const chunk of chunks) { const dataLine = chunk.split('\n').find((line) => line.startsWith('data:')); if (!dataLine) continue; try { const payload = JSON.parse(dataLine.slice(5)); if (payload.type === 'reply' && payload.payload?.content) setChatMessages((items) => { const next = [...items]; next[next.length - 1] = { role: 'assistant', content: payload.payload.content, references: payload.payload.quote_infos || payload.payload.file_infos || [] }; return next; }); } catch { /* ignore non-JSON keepalive events */ } } } } catch (e) { setChatMessages((items) => { const next = [...items]; next[next.length - 1] = { role: 'assistant', content: `暂时无法回答：${e.message}` }; return next; }); } finally { setChatting(false); } };
  const shownFiles = files.filter((file) => file.name.toLowerCase().includes(query.toLowerCase()));
  const crumbs = prefix ? prefix.split('/').filter(Boolean) : [];
  return <div className="storage-app"><header><div className="logo">KB</div><div><b>717知识库</b><small>ADP 智能体 · COS 素材库</small></div><div className="header-spacer" /><button className="refresh" onClick={load}><RefreshCw size={16} />刷新</button><button className="new-folder" onClick={createFolder}><FolderPlus size={16} />新建文件夹</button><button className="upload" onClick={() => input.current?.click()}><Upload size={16} />上传</button><input ref={input} hidden type="file" multiple onChange={upload} /></header>
    <main><div className="bar"><div className="crumbs"><button className={searchMode === 'browse' ? 'active' : ''} onClick={() => setSearchMode('browse')}>文件浏览</button><button className={searchMode === 'semantic' ? 'active' : ''} onClick={() => setSearchMode('semantic')}><Sparkles size={13} />多模态搜索</button><button className={searchMode === 'chat' ? 'active' : ''} onClick={() => setSearchMode('chat')}><MessageCircle size={13} />知识库问答</button>{searchMode === 'browse' && <>{prefix ? prefix.split('/').filter(Boolean).map((crumb, index, arr) => <React.Fragment key={crumb}><ChevronRight size={14} /><button onClick={() => setPrefix(`${arr.slice(0, index + 1).join('/')}/`)}>{crumb}</button></React.Fragment>) : <span className="root-label">根目录</span>}</>}</div>{searchMode !== 'chat' && <form className="search" onSubmit={searchMode === 'semantic' ? semanticSearch : (e) => e.preventDefault()}><Search size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder={searchMode === 'semantic' ? '描述你要找的内容，例如：红旗活动现场' : '搜索当前目录'} />{searchMode === 'semantic' && <select value={searchType} onChange={(e) => setSearchType(e.target.value)} aria-label="搜索类型"><option value="image">图片</option><option value="video">视频</option><option value="document">文档</option><option value="all">全部</option></select>}</form>}{searchMode === 'chat' && <form className="search" onSubmit={sendChat}><MessageCircle size={16} /><input value={chatQuery} onChange={(e) => setChatQuery(e.target.value)} placeholder="向 717 知识库提问" disabled={chatting} /><button className="send-chat" disabled={chatting || !chatQuery.trim()}>{chatting ? '回答中' : '发送'}</button></form>}</div>
      {uploading > 0 && <div className="uploading"><Upload size={16} />正在上传 {uploading} 个文件…</div>}
      {searchMode === 'chat' ? <div className="chat-panel">{!chatMessages.length && <div className="empty">可以询问活动事实、传播主题和素材说明</div>}{chatMessages.map((message, index) => <div className={`chat-message ${message.role}`} key={`${index}-${message.content.slice(0, 8)}`}><span>{message.role === 'user' ? '你' : '717 知识库'}</span><p>{message.content || (chatting ? '正在检索知识库…' : '')}</p></div>)}</div> : searchMode === 'semantic' ? <div className="table semantic-results"><div className="thead"><span>匹配对象</span><span>相关度</span><span>命中内容</span><span /></div>{searching ? <div className="empty">正在调用 MetaInsight…</div> : searchError ? <div className="empty search-fail">{searchError}</div> : !query ? <div className="empty">输入描述后搜索图片、视频或文档内容</div> : !results.length ? <div className="empty">没有找到匹配对象</div> : results.map((item) => <div className="row" key={item.uri}><span className="name"><Sparkles size={18} className="file" /><b title={item.uri}>{item.uri.replace(/^cos:\/\/[^/]+\//, '')}</b></span><span>{item.score ? item.score.toFixed(3) : '—'}</span><span title={item.text}>{item.text || '语义匹配'}</span><span /></div>)}</div> : error ? <div className="error"><b>连接存储服务失败</b><span>{error}</span><button onClick={load}>重试</button></div> : <div className="table"><div className="thead"><span>名称</span><span>大小</span><span>修改时间</span><span /></div>{loading ? <div className="empty">正在读取桶内容…</div> : !folders.length && !shownFiles.length ? <div className="empty">当前目录为空</div> : <>{folders.map((folder) => <div className="row" key={folder} onDoubleClick={() => setPrefix(folder)}><span className="name"><Folder size={19} className="folder" /><b>{folder.slice(prefix.length).replace(/\/$/, '') || folder}</b></span><span>—</span><span>—</span><button className="delete" title="删除文件夹及全部内容" onClick={() => removeFolder(folder)}><Trash2 size={15} /></button></div>)}{shownFiles.map((file) => { const Icon = fileIcon(file.name); return <div className="row" key={file.key}><span className="name"><Icon size={19} className="file" /><b title={file.name}>{file.name}</b></span><span>{formatSize(file.size)}</span><span>{new Date(file.updated).toLocaleString('zh-CN', { month: 'numeric', day: 'numeric', hour: '2-digit', minute: '2-digit' })}</span><button className="delete" title="删除" onClick={() => remove(file.key)}><Trash2 size={15} /></button></div>; })}</>}</div>}
      <footer><span>{searchMode === 'semantic' ? `${results.length} 个匹配对象` : searchMode === 'chat' ? `${chatMessages.filter((item) => item.role === 'user').length} 个问题` : `${folders.length + shownFiles.length} 个对象`}</span><span>{searchMode === 'semantic' ? '由腾讯云 MetaInsight 提供语义检索' : searchMode === 'chat' ? '由腾讯云 ADP 智能体提供回答' : '双击文件夹进入目录'}</span></footer>
    </main></div>;
}
createRoot(document.getElementById('root')).render(<App />);
